/**
 * Source export.
 *
 * The generated project is genuinely multi-file, so the export is a real zip of
 * those files — not a screenshot of a code panel. A short README and a
 * single-document build are bundled alongside so the folder is runnable both by
 * opening `index.html` and by double-clicking the standalone build.
 */

import type { ProjectFile } from './client';
import { ENTRY_FILE, bundleForPreview, totalChars } from './bundler';

/** Turn a project name into a safe file stem. */
export function slugifyName(name: string): string {
  const cleaned = (name || '')
    .trim()
    .replace(/[\\/:*?"<>|]+/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 48);
  return cleaned || 'atomforge-project';
}

function readme(name: string, files: ProjectFile[], note: string): string {
  const list = files.map((file) => `- \`${file.path}\` — ${file.content.split('\n').length} 行`);
  return `# ${name}

由 AtomForge 生成的原生前端项目，无需构建、无需安装依赖。

## 怎么运行

直接用浏览器打开 \`${ENTRY_FILE}\` 即可。
如果只想拿一个能到处发的单文件版本，用 \`standalone.html\`（已把本地样式与脚本内联进同一个文档）。

## 文件说明

${list.join('\n')}

共 ${files.length} 个文件、${totalChars(files)} 个字符。

## 版本备注

${note.trim() || '（导出时未填写备注）'}

## 二次修改建议

- 改外观只动 \`.css\` 文件，改行为只动 \`.js\` 文件，结构调整才碰 \`${ENTRY_FILE}\`。
- 外部资源只使用了 CDN 链接，离线环境下相关样式或图片可能不显示。

---
Generated by AtomForge.
`;
}

export interface ExportResult {
  filename: string;
  bytes: number;
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Give Safari a beat before revoking, otherwise the download can abort.
  window.setTimeout(() => URL.revokeObjectURL(url), 2000);
}

/**
 * Export the whole project as a zip. JSZip is imported lazily so the workspace
 * bundle stays small for users who never export.
 */
export async function exportProjectZip(
  name: string,
  files: ProjectFile[],
  note = '',
): Promise<ExportResult> {
  if (!files.length) throw new Error('项目还没有任何文件可以导出');

  const { default: JSZip } = await import('jszip');
  const stem = slugifyName(name);
  const zip = new JSZip();
  const folder = zip.folder(stem) || zip;

  files.forEach((file) => folder.file(file.path, file.content));
  folder.file('README.md', readme(name || stem, files, note));

  const standalone = bundleForPreview(files);
  if (standalone.trim()) folder.file('standalone.html', standalone);

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  const filename = `${stem}.zip`;
  triggerDownload(blob, filename);
  return { filename, bytes: blob.size };
}

/** Export just the file currently open in the code panel. */
export function exportSingleFile(file: ProjectFile): ExportResult {
  const blob = new Blob([file.content], { type: 'text/plain;charset=utf-8' });
  const filename = file.path.split('/').pop() || 'file.txt';
  triggerDownload(blob, filename);
  return { filename, bytes: blob.size };
}

/** Export the runnable single-document build on its own. */
export function exportStandalone(name: string, files: ProjectFile[]): ExportResult {
  const html = bundleForPreview(files);
  if (!html.trim()) throw new Error('还没有可运行的页面');
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const filename = `${slugifyName(name)}-standalone.html`;
  triggerDownload(blob, filename);
  return { filename, bytes: blob.size };
}