"""auto update

Revision ID: 258b4b099ee9
Revises: 9db2844a4536
Create Date: 2026-08-14 08:29:10.258949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258b4b099ee9'
down_revision: Union[str, Sequence[str], None] = '9db2844a4536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('workspace_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_messages_account_id'), 'workspace_messages', ['account_id'], unique=False)
    op.create_index(op.f('ix_workspace_messages_id'), 'workspace_messages', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_messages_workspace_id'), 'workspace_messages', ['workspace_id'], unique=False)
    op.create_table('workspace_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('files_json', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_versions_account_id'), 'workspace_versions', ['account_id'], unique=False)
    op.create_index(op.f('ix_workspace_versions_id'), 'workspace_versions', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_versions_workspace_id'), 'workspace_versions', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('files_json', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('share_slug', sa.String(), nullable=True),
    sa.Column('version_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_account_id'), 'workspaces', ['account_id'], unique=False)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_account_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_workspace_versions_workspace_id'), table_name='workspace_versions')
    op.drop_index(op.f('ix_workspace_versions_id'), table_name='workspace_versions')
    op.drop_index(op.f('ix_workspace_versions_account_id'), table_name='workspace_versions')
    op.drop_table('workspace_versions')
    op.drop_index(op.f('ix_workspace_messages_workspace_id'), table_name='workspace_messages')
    op.drop_index(op.f('ix_workspace_messages_id'), table_name='workspace_messages')
    op.drop_index(op.f('ix_workspace_messages_account_id'), table_name='workspace_messages')
    op.drop_table('workspace_messages')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###