"""auto update

Revision ID: 837cf615e5b4
Revises: c63501068730
Create Date: 2026-08-14 22:54:06.798474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837cf615e5b4'
down_revision: Union[str, Sequence[str], None] = 'c63501068730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('files_json', sa.String(), nullable=False),
    sa.Column('source_workspace_id', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_templates_account_id'), 'user_templates', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_templates_id'), 'user_templates', ['id'], unique=False)
    op.create_index(op.f('ix_user_templates_source_workspace_id'), 'user_templates', ['source_workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_templates_source_workspace_id'), table_name='user_templates')
    op.drop_index(op.f('ix_user_templates_id'), table_name='user_templates')
    op.drop_index(op.f('ix_user_templates_account_id'), table_name='user_templates')
    op.drop_table('user_templates')
    # ### end Alembic commands ###