"""auto update

Revision ID: c63501068730
Revises: 258b4b099ee9
Create Date: 2026-08-14 21:11:30.786233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63501068730'
down_revision: Union[str, Sequence[str], None] = '258b4b099ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_versions', sa.Column('note', sa.String(), nullable=True))
    op.add_column('workspace_versions', sa.Column('audit_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_versions', 'audit_json')
    op.drop_column('workspace_versions', 'note')
    # ### end Alembic commands ###